modLoader="javafml"
loaderVersion="[44,)"
license="(c)2021 gray27 All rights reserved"
issueTrackerURL="https://github.com/graycat27/FlightHUD/issues"
[[mods]]
modId="flighthudmod"
version="${file.jarVersion}"
displayName="FlightHUD"
updateJSONURL="https://raw.githubusercontent.com/graycat27/FlightHUD/forgeMaster/project/src/main/resources/version.json"
credits="Have a nice flight"
authors="gray27"
description='''
'''
[[dependencies.flighthudmod]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.flighthudmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="CLIENT"
