modLoader="javafml"
loaderVersion="[39,)"
license="(c)2021 gray27 All rights reserved"
issueTrackerURL="https://github.com/graycat27/FlightHUD/issues"
[[mods]]
modId="flighthudmod"
version="${file.jarVersion}"
displayName="FlightHUD"
credits="Have a nice flight"
authors="gray27"
description='''
'''
[[dependencies.flighthudmod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.flighthudmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="CLIENT"
